# [Practice Pandas]

*KU LeeDongGyu*

## Examples
---

In [2]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [3]:
#pandas 설치하면 numpy도 자동설치됨.
import numpy as np
import pandas as pd

### Object Creation

In [7]:
s = pd.Series([1,3,5,np.nan,6,8]) #NaN 출력 봐놓기
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


In [6]:
dates = pd.date_range('20130101', periods=6)
print(dates)
print("***")
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD')) #index는 타입상관없음.
print(df)
#dates = ['1','2','3','4','5','6'] #문자
#dates = [int(i) for i in aa ] #정수 다 인덱스로 받음.

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')
***
                   A         B         C         D
2013-01-01 -1.286662  2.216221 -0.265969  0.511096
2013-01-02  0.052720  0.624139 -0.828565  0.812432
2013-01-03 -0.221770  0.253779 -3.137794  1.113647
2013-01-04 -0.164101 -1.111523  1.010428 -1.079208
2013-01-05 -0.419323 -0.197844 -1.871331 -0.351558
2013-01-06  1.202883 -0.230332 -0.570591 -0.543233


In [9]:
df2 = pd.DataFrame({ 'A' : 1.,
                     'B' : pd.Timestamp('20130102'),
                     'C' : pd.Series(1,index=list(range(4)),dtype='float32'), #type을 실수형 32비트
                     'D' : np.array([3] * 4,dtype='int32'), #정수형 32비트는 초기값.
                     'E' : pd.Categorical(["test","train","test","train"]),
                     'F' : 'foo' })
print(df2) #카테고리 빼고 리스트를 써도되나, 그러면 범주가 아님!
print("***")
print(df2.dtypes)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo
***
A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object


### Viewing Data

In [10]:
print(df.head())
print("***")
print(df.tail(3))

                   A         B         C         D
2013-01-01 -1.286662  2.216221 -0.265969  0.511096
2013-01-02  0.052720  0.624139 -0.828565  0.812432
2013-01-03 -0.221770  0.253779 -3.137794  1.113647
2013-01-04 -0.164101 -1.111523  1.010428 -1.079208
2013-01-05 -0.419323 -0.197844 -1.871331 -0.351558
***
                   A         B         C         D
2013-01-04 -0.164101 -1.111523  1.010428 -1.079208
2013-01-05 -0.419323 -0.197844 -1.871331 -0.351558
2013-01-06  1.202883 -0.230332 -0.570591 -0.543233


In [11]:
print(df.index) #인덱스 보여줌.
print("***")
print(df.columns) #컬럼 보여줌
print("***")
print(df.values) #값 보여줌


DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')
***
Index(['A', 'B', 'C', 'D'], dtype='object')
***
[[-1.28666227  2.21622081 -0.26596854  0.51109608]
 [ 0.05271963  0.62413894 -0.82856506  0.81243188]
 [-0.22176952  0.25377917 -3.13779425  1.11364741]
 [-0.16410104 -1.11152279  1.01042801 -1.07920828]
 [-0.41932344 -0.1978445  -1.87133124 -0.35155764]
 [ 1.20288292 -0.23033161 -0.57059109 -0.54323302]]


In [12]:
print(df.describe()) #R의 summary함수.
print(df.T)
print(df.sort_index(axis=1, ascending=False)) #1이면 가로(행), 0이면 세로(열), 왼쪽은 내림차순정렬
print(df.sort_values(by='B')) #아래로 내려갈수록 오름차순.

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.139376  0.259073 -0.943970  0.077196
std    0.805059  1.121655  1.421615  0.861290
min   -1.286662 -1.111523 -3.137794 -1.079208
25%   -0.369935 -0.222210 -1.610640 -0.495314
50%   -0.192935  0.027967 -0.699578  0.079769
75%   -0.001486  0.531549 -0.342124  0.737098
max    1.202883  2.216221  1.010428  1.113647
   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A   -1.286662    0.052720   -0.221770   -0.164101   -0.419323    1.202883
B    2.216221    0.624139    0.253779   -1.111523   -0.197844   -0.230332
C   -0.265969   -0.828565   -3.137794    1.010428   -1.871331   -0.570591
D    0.511096    0.812432    1.113647   -1.079208   -0.351558   -0.543233
                   D         C         B         A
2013-01-01  0.511096 -0.265969  2.216221 -1.286662
2013-01-02  0.812432 -0.828565  0.624139  0.052720
2013-01-03  1.113647 -3.137794  0.253779 -0.221770
2013-01-04 -

### Selection

In [13]:
print(df['A']) #문자로 쓰면 열들을 뽑으라는것. (기본)
print(df[['A','B']]) # = print(df.loc[:,['A','B']])
print("***")

2013-01-01   -1.286662
2013-01-02    0.052720
2013-01-03   -0.221770
2013-01-04   -0.164101
2013-01-05   -0.419323
2013-01-06    1.202883
Freq: D, Name: A, dtype: float64
                   A         B
2013-01-01 -1.286662  2.216221
2013-01-02  0.052720  0.624139
2013-01-03 -0.221770  0.253779
2013-01-04 -0.164101 -1.111523
2013-01-05 -0.419323 -0.197844
2013-01-06  1.202883 -0.230332
***


In [14]:
print(df[0:1]) #행을 뽑고 싶으면 반드시 이렇게 범위로 써야함.
print(df.loc[dates[0]])  #print(df[0:1][:].T) 와 유사. df[행][열]
#데이터로서 표시할때는 이렇게.
print(df.loc[:,['A','B']]) #뽑을때는 loc함수 쓸것.얘는 이름으로뽑음.

                   A         B         C         D
2013-01-01 -1.286662  2.216221 -0.265969  0.511096
A   -1.286662
B    2.216221
C   -0.265969
D    0.511096
Name: 2013-01-01 00:00:00, dtype: float64
                   A         B
2013-01-01 -1.286662  2.216221
2013-01-02  0.052720  0.624139
2013-01-03 -0.221770  0.253779
2013-01-04 -0.164101 -1.111523
2013-01-05 -0.419323 -0.197844
2013-01-06  1.202883 -0.230332


In [15]:
print(df.loc['20130102':'20130104',['A','B']]) #==print(df[1:4][['A','B']])
#print(df[1:4][1:2])는 [1:4]뽑은것 중 [1:2]를 의미.
#print(df[1:4][['A','B']]) == print(df[1:4][df.columns[0:2]]) 임. 불편하지만 받아들이기.
#==print(df.loc[dates[1:4],['A','B']])
# print(df.loc[1:3,['A','B']]) 얘는 안됨.

                   A         B
2013-01-02  0.052720  0.624139
2013-01-03 -0.221770  0.253779
2013-01-04 -0.164101 -1.111523


In [16]:
print(df.iloc[3]) #== print(df.loc[dates[3]])
print(df.iloc[[1,2,4],[0,2]]) #얘는 index로 뽑는거임.
print(df[df.A > 0]) ## df.A는 df변수의 A컬럼이라는 뜻임. 자동지정되므로 참고하기!


A   -0.164101
B   -1.111523
C    1.010428
D   -1.079208
Name: 2013-01-04 00:00:00, dtype: float64
                   A         C
2013-01-02  0.052720 -0.828565
2013-01-03 -0.221770 -3.137794
2013-01-05 -0.419323 -1.871331
                   A         B         C         D
2013-01-02  0.052720  0.624139 -0.828565  0.812432
2013-01-06  1.202883 -0.230332 -0.570591 -0.543233


In [17]:
print(df)
print("***")
s1 = pd.Series([1,2,3,4,5,6], index=pd.date_range('20130102', periods=6))
df['F'] = s1 #기존 df의 변수에 대해서만 추가를 시킴.
#df.F = s1 생성하면서 동시에 넣는건 위에서나 가능. 왼쪽에서처럼은 불가능.
print(df)


                   A         B         C         D
2013-01-01 -1.286662  2.216221 -0.265969  0.511096
2013-01-02  0.052720  0.624139 -0.828565  0.812432
2013-01-03 -0.221770  0.253779 -3.137794  1.113647
2013-01-04 -0.164101 -1.111523  1.010428 -1.079208
2013-01-05 -0.419323 -0.197844 -1.871331 -0.351558
2013-01-06  1.202883 -0.230332 -0.570591 -0.543233
***
                   A         B         C         D    F
2013-01-01 -1.286662  2.216221 -0.265969  0.511096  NaN
2013-01-02  0.052720  0.624139 -0.828565  0.812432  1.0
2013-01-03 -0.221770  0.253779 -3.137794  1.113647  2.0
2013-01-04 -0.164101 -1.111523  1.010428 -1.079208  3.0
2013-01-05 -0.419323 -0.197844 -1.871331 -0.351558  4.0
2013-01-06  1.202883 -0.230332 -0.570591 -0.543233  5.0


In [18]:
df.loc[:,'D'] = 5 #바꾸는건 이렇게
print(df)

                   A         B         C  D    F
2013-01-01 -1.286662  2.216221 -0.265969  5  NaN
2013-01-02  0.052720  0.624139 -0.828565  5  1.0
2013-01-03 -0.221770  0.253779 -3.137794  5  2.0
2013-01-04 -0.164101 -1.111523  1.010428  5  3.0
2013-01-05 -0.419323 -0.197844 -1.871331  5  4.0
2013-01-06  1.202883 -0.230332 -0.570591  5  5.0


### Missing Data

In [19]:
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ['E']) #index만 바꿔서 다시 데이터를 만들때
df1.loc[dates[0:2],'E'] = 1
print(df1)

print(df1.dropna(how='any')) #NaN하나라도 있으면 버리기
print(df1.fillna(value=5)) #NaN을 값5로 넣기 (데이터변수.na처리함수)
print(pd.isna(df1)) #na가 있는것을 보기. 이때 pd.isna method임을 알고있기.


                   A         B         C  D    F    E
2013-01-01 -1.286662  2.216221 -0.265969  5  NaN  1.0
2013-01-02  0.052720  0.624139 -0.828565  5  1.0  1.0
2013-01-03 -0.221770  0.253779 -3.137794  5  2.0  NaN
2013-01-04 -0.164101 -1.111523  1.010428  5  3.0  NaN
                  A         B         C  D    F    E
2013-01-02  0.05272  0.624139 -0.828565  5  1.0  1.0
                   A         B         C  D    F    E
2013-01-01 -1.286662  2.216221 -0.265969  5  5.0  1.0
2013-01-02  0.052720  0.624139 -0.828565  5  1.0  1.0
2013-01-03 -0.221770  0.253779 -3.137794  5  2.0  5.0
2013-01-04 -0.164101 -1.111523  1.010428  5  3.0  5.0
                A      B      C      D      F      E
2013-01-01  False  False  False  False   True  False
2013-01-02  False  False  False  False  False  False
2013-01-03  False  False  False  False  False   True
2013-01-04  False  False  False  False  False   True


### Operations

In [20]:
print(df.mean()) # == print(df.mean(0))
print("***")
print(df.mean(1))

A   -0.139376
B    0.259073
C   -0.943970
D    5.000000
F    3.000000
dtype: float64
***
2013-01-01    1.415898
2013-01-02    1.169659
2013-01-03    0.778843
2013-01-04    1.546961
2013-01-05    1.302300
2013-01-06    2.080392
Freq: D, dtype: float64


In [21]:
s = pd.Series([1,3,5,np.nan,6,8], index=dates)
print(s)
print("***")
print(s.shift(2)) #데이터들을 아래로 2칸 옮김
print("***")
print(s.shift(-1)) #데이터들을 위로 1칸 옮김. 빈칸은 NaN


2013-01-01    1.0
2013-01-02    3.0
2013-01-03    5.0
2013-01-04    NaN
2013-01-05    6.0
2013-01-06    8.0
Freq: D, dtype: float64
***
2013-01-01    NaN
2013-01-02    NaN
2013-01-03    1.0
2013-01-04    3.0
2013-01-05    5.0
2013-01-06    NaN
Freq: D, dtype: float64
***
2013-01-01    3.0
2013-01-02    5.0
2013-01-03    NaN
2013-01-04    6.0
2013-01-05    8.0
2013-01-06    NaN
Freq: D, dtype: float64


In [22]:
print(df)
print("***")
print(df.apply(np.cumsum)) # == print(df.apply(np.cumsum, axis=0)) a
print("***")
print(df.apply(np.cumsum, axis=1))
print("***")
print(df.apply(lambda x: x.max() - x.min())) #lambda x는 함수명령어.(아마 매틀랩에서 배운듯)
#즉, 괄호에는 함수가 들어간다는 뜻
#print(df.apply(sum, axis=1)) <--- apply함수는 괄호안의 첫번째에 함수를받고, 두번째에 시행하는방향.
#R의 apply문과 비슷.


                   A         B         C  D    F
2013-01-01 -1.286662  2.216221 -0.265969  5  NaN
2013-01-02  0.052720  0.624139 -0.828565  5  1.0
2013-01-03 -0.221770  0.253779 -3.137794  5  2.0
2013-01-04 -0.164101 -1.111523  1.010428  5  3.0
2013-01-05 -0.419323 -0.197844 -1.871331  5  4.0
2013-01-06  1.202883 -0.230332 -0.570591  5  5.0
***
                   A         B         C   D     F
2013-01-01 -1.286662  2.216221 -0.265969   5   NaN
2013-01-02 -1.233943  2.840360 -1.094534  10   1.0
2013-01-03 -1.455712  3.094139 -4.232328  15   3.0
2013-01-04 -1.619813  1.982616 -3.221900  20   6.0
2013-01-05 -2.039137  1.784772 -5.093231  25  10.0
2013-01-06 -0.836254  1.554440 -5.663822  30  15.0
***
                   A         B         C         D          F
2013-01-01 -1.286662  0.929559  0.663590  5.663590        NaN
2013-01-02  0.052720  0.676859 -0.151706  4.848294   5.848294
2013-01-03 -0.221770  0.032010 -3.105785  1.894215   3.894215
2013-01-04 -0.164101 -1.275624 -0.265196  4.

### Merge

In [23]:
print(df)
print("***")
s = df.iloc[3] #4번째행이 출력됨.
print(df.append(s, ignore_index=True)) #append명령어를 써서 출력
#print(df.append(s, ignore_index=False)) 이건 인덱스를 고스란히 출력하라는 뜻.
#맨 아래행에 데이터가 추가된다.


                   A         B         C  D    F
2013-01-01 -1.286662  2.216221 -0.265969  5  NaN
2013-01-02  0.052720  0.624139 -0.828565  5  1.0
2013-01-03 -0.221770  0.253779 -3.137794  5  2.0
2013-01-04 -0.164101 -1.111523  1.010428  5  3.0
2013-01-05 -0.419323 -0.197844 -1.871331  5  4.0
2013-01-06  1.202883 -0.230332 -0.570591  5  5.0
***
          A         B         C    D    F
0 -1.286662  2.216221 -0.265969  5.0  NaN
1  0.052720  0.624139 -0.828565  5.0  1.0
2 -0.221770  0.253779 -3.137794  5.0  2.0
3 -0.164101 -1.111523  1.010428  5.0  3.0
4 -0.419323 -0.197844 -1.871331  5.0  4.0
5  1.202883 -0.230332 -0.570591  5.0  5.0
6 -0.164101 -1.111523  1.010428  5.0  3.0


In [24]:
left = pd.DataFrame({'key': ['foo', 'bar'], 'rval': [4, 5]})
right = pd.DataFrame({'key': ['foo', 'bar'], 'rval': [4, 5] , 'abs': ['foo', 'bar']} )
print(left)
print("***")
print(right)
print("***")
print(pd.merge(left, right, on='key')) #  print(pd.merge(left, right)) 얘는 최대한 다겹쳐서 출력.
# merge는 항상 기준이 있어야함.
#print(pd.merge(left, right, on='key')) 이러면 중복은 key만 취급. (key가 기준)

   key  rval
0  foo     4
1  bar     5
***
   key  rval  abs
0  foo     4  foo
1  bar     5  bar
***
   key  rval_x  rval_y  abs
0  foo       4       4  foo
1  bar       5       5  bar


### Grouping

In [26]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar', 'foo', 'bar', 'foo', 'foo'],
                   'B' : ['one', 'one', 'two', 'three', 'two', 'two', 'one', 'three'],
                   'C' : np.random.randn(8),
                   'D' : np.random.randn(8)})
print(df)

     A      B         C         D
0  foo    one  1.404458 -0.296578
1  bar    one -0.510053  1.408224
2  foo    two -1.119213 -0.587399
3  bar  three  0.406430  0.632027
4  foo    two  1.429356 -0.184191
5  bar    two -0.024648 -0.881995
6  foo    one  0.564534 -1.760849
7  foo  three -0.996121 -0.138044


In [27]:
print(df.groupby('A').sum()) #더할수 있게되는 숫자들만 더함.
print(df.groupby(['A','B']).sum()) #A,B순서쌍에 대한 그룹들에서 더함

            C         D
A                      
bar -0.128271  1.158257
foo  1.283014 -2.967061
                  C         D
A   B                        
bar one   -0.510053  1.408224
    three  0.406430  0.632027
    two   -0.024648 -0.881995
foo one    1.968992 -2.057427
    three -0.996121 -0.138044
    two    0.310143 -0.771589


### Getting Data In/Out

In [28]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))
# df.to_csv('foo.csv') #df를 csv로 보낸다 => df.to_csv 를 씀. 실행하지는 않음.

In [ ]:
#pd.read_csv('foo.csv') #read_csv는 pd의 함수.
#pd.read_csv('foo.csv', index_col=0) #index로 지정한 col은 0번째라는 뜻.
#역시나 실행하지는 않았다. 이렇게