# [Chapter 4 ~ 5 ]

*KU LeeDongGyu*

## 1. Multi Variable Linear Regression
___

### 1-1) Naive

In [1]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

In [2]:
#Data
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

In [3]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

In [4]:
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b #bias 추가

In [5]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [7]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
#0.01 말고 1e-5정도로 줌.
train = optimizer.minimize(cost)

In [9]:
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 400 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  62547.29 
Prediction:
 [-75.96345  -78.27629  -83.83015  -90.80436  -56.976482]
400 Cost:  11.298648 
Prediction:
 [146.46979 188.03654 179.11147 195.46513 145.95143]
800 Cost:  9.147448 
Prediction:
 [146.96248 187.69937 179.26315 195.5693  145.51363]
1200 Cost:  7.415207 
Prediction:
 [147.4048  187.39668 179.39937 195.66235 145.12111]
1600 Cost:  6.020313 
Prediction:
 [147.80191 187.125   179.52174 195.74542 144.7692 ]
2000 Cost:  4.897013 
Prediction:
 [148.15846 186.88112 179.63167 195.81955 144.45374]


### 1-2) Using Matrix

In [16]:
###위처럼 하지말자. 아래처럼 행렬을 쓰자.###


# Lab 4 Multi-variable linear regression
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]
#데이터는 실수타입이다.

In [10]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
#shape에 none을 주고 데이터를 무한정 받을수 있다는것에 주목하자.
#n개를 지닐것이다라는 것을 의미함. numpy에서는 None대신 -1을 넣으면 됨.
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [11]:
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
#tf 에서는 random_normal 난수임. (3X1)차원을 주면서 초기치 생성.
b = tf.Variable(tf.random_normal([1]), name='bias')

In [12]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

In [13]:
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [14]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [17]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 400 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  56385.383 
Prediction:
 [[-58.458183]
 [-68.912796]
 [-68.368965]
 [-77.117615]
 [-50.047314]]
400 Cost:  0.9865249 
Prediction:
 [[152.238  ]
 [184.32083]
 [181.14893]
 [194.61884]
 [143.08952]]
800 Cost:  0.9700853 
Prediction:
 [[152.23997]
 [184.31773]
 [181.14731]
 [194.63477]
 [143.07106]]
1200 Cost:  0.95411456 
Prediction:
 [[152.24106]
 [184.31532]
 [181.14545]
 [194.65038]
 [143.05363]]
1600 Cost:  0.9385697 
Prediction:
 [[152.24126]
 [184.31346]
 [181.14333]
 [194.6656 ]
 [143.03706]]
2000 Cost:  0.9234179 
Prediction:
 [[152.24075]
 [184.31216]
 [181.14102]
 [194.68056]
 [143.02135]]


## 2. Loading Data From File
---

### 2-1) Using Numpy

In [4]:
import tensorflow as tf
import numpy  as np
tf.set_random_seed(777)  # for reproducibility

In [5]:
xy = np.loadtxt('/Users/82104/Desktop/data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:,0:-1] #넘파이에서 가져오면 이렇게됨.
y_data = xy[:, [-1]] #넘파이에서 가져오면 이렇게됨.

In [6]:
print(x_data, "\nx_data shape:", x_data.shape) #넘파이 매서드
print(y_data, "\ny_data shape:", y_data.shape)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
y_data shape: (25, 1)


In [7]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')
# w = tf.Variable([3,1],dtype=tf.float32 , name = "weight") 
#이렇게하면 shape가 결정이 안됨. 괜히 random주는게 아님.
# b = tf.Variable([2],dtype = tf.float32 , name = 'error')

In [8]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b
#주의!! matmul은 numpy의 numpy.dot과는 다르다. (@와는 다름.) <- 2차원에서만 같음.
#matmul은 np에도 있고 tf에도 있음. 아마 두 사용은 거의 같을 것으로 사료됨.
#참고 : http://blog.naver.com/PostView.nhn?blogId=cjh226&logNo=221356884894&categoryNo=17&parentCategoryNo=0&viewDate=&currentPage=1&postListTopCurrentPage=1&from=search
#우리는 2차원 행렬 그 이상의 것을 다루기에, 반드시 matmul을 써야함.
# Simplified cost/loss function

cost = tf.reduce_mean(tf.square(hypothesis - Y))
#sum을 해도 되나, 이 경우 learning_rate를 더 작게 줘야함.

In [9]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
# 1e-5정도면 작은것도 아님. 이는 다차원이기 때문에그럼
train = optimizer.minimize(cost)


In [11]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001) :
         _ , C , F , w, B = \
             sess.run([train,cost,hypothesis,W,b],feed_dict={X:x_data , Y:y_data})
         #함수에 대한 값을 알고싶으면 f
         #w,b에 대한 값도 역시나 위처럼 살펴본다.
         if step % 400 == 0 :
             print(step, "Cost:", C , "\nCoefficients\n" , w , '\nError\n', B, "\nPrediction:\n",F )


0 Cost: 149081.62 
Coefficients
 [[-0.68651825]
 [-0.2543735 ]
 [ 0.05992556]] 
Error
 [-0.70932484] 
Prediction:
 [[-208.96912]
 [-252.386  ]
 [-248.07109]
 [-269.068  ]
 [-193.84889]
 [-141.66081]
 [-199.65695]
 [-145.46127]
 [-234.968  ]
 [-215.51793]
 [-193.85843]
 [-191.36353]
 [-257.3588 ]
 [-215.64026]
 [-200.66075]
 [-254.98555]
 [-207.08858]
 [-238.49321]
 [-245.34242]
 [-219.26062]
 [-234.57315]
 [-235.71355]
 [-223.8603 ]
 [-213.20384]
 [-261.81982]]
400 Cost: 6.6421175 
Coefficients
 [[0.27823278]
 [0.6827523 ]
 [1.0621177 ]] 
Error
 [-0.69793874] 
Prediction:
 [[153.89246]
 [184.03665]
 [181.78598]
 [199.13394]
 [139.0227 ]
 [103.87103]
 [150.80688]
 [114.34024]
 [173.03583]
 [162.54065]
 [143.82733]
 [141.75357]
 [186.69217]
 [153.43759]
 [151.46437]
 [187.90569]
 [144.43494]
 [182.06369]
 [177.94226]
 [159.45612]
 [176.42444]
 [173.74396]
 [167.95274]
 [152.52722]
 [190.40948]]
800 Cost: 6.463309 
Coefficients
 [[0.2851969 ]
 [0.66126543]
 [1.0763526 ]] 
Error
 [-0.69842

### 2-2) Using Pandas

In [27]:
import tensorflow as tf
import pandas as pd
import numpy as np
tf.set_random_seed(777)  # for reproducibility
#R과 조금 다르다. 777에 해당하는 난수가 늘 고정되는게 아님. 다만, 이렇게 설정해놓으면
#이러한 숫자 설정 상황 내에서 '처음' 숫자가 고정됨.
#얘를 시행히시킬 때마다 각 집단간의 스타트 숫자는 늘 바뀜. 다시말해 아래와 다른 random seed이다.
# import random
# random.seed(1
)
# random.random()

In [28]:
xy = pd.read_csv("/Users/82104/Desktop/data-01-test-score.csv", header = None) #그밖에 sep , index_col 옵션이 있음.
x_data=xy.iloc[:,0:-1] #판다스에서 가져오면 이렇게
y_data = xy.iloc[:,[-1]]
#y_data = data.iloc[:,-1] #얘와의 차이점을 잘 알아놓기. 얘는 (25, ) 인 벡터임. 다시말해 얘는 안됨.

#x_data.head()
#y_data.head()
#이후 동일.

### 2-3) Advanced Course - Queue Filing

In [13]:
import tensorflow as tf
import os
os.chdir("/Users/82104/Desktop/") #미리 경로설정.
tf.set_random_seed(777)  # for reproducibility

In [14]:
filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue')
#파일들을 쌓아서 불러올수 있음.
#파일들의 리스트를 함수 처음에 받음. 이경우 1개임.
#실제로는 데이터가 매우 크기때문에, 이렇게 나눠서 읽어들이게 됨.
#매번 학습시 데이터가 편향되지 않게 랜덤하게 나오려면 shuffle = True

In [15]:
reader = tf.TextLineReader() #텍스트를 읽을꺼임. 문자든, 숫자든 어쨋든 데이터면 텍스트.
key, value = reader.read(filename_queue) #텍스트 파일을 읽을때 일반적으로 사용.
#다음 사이트를 참고하면 더 쉽게 이해할 수 있다. https://bcho.tistory.com/1165

In [16]:
record_defaults = [[0.], [0.], [0.], [0.]] #floating point 정의
#각 영역의 default를 정의하므로써, 데이터 타입 및 필드의 초기값을 얘기해줌.
#필드에 값이 비어있으면, 이 디폴트값이 채워진다. 중요한작업.
xy = tf.decode_csv(value, record_defaults=record_defaults)
#value를 csv로 decode 해라 라는 뜻. 이로써 xy에 decode된 값들이 파싱됨.

In [17]:
# collect batches of csv in
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10) #10개씩 가져옴.
#일종의 펌프같은 역할. batch를 통해 데이터를 배치한다.
#여기까지가 불러오는 방법임.

W0813 13:10:20.247239  8112 deprecation.py:323] From <ipython-input-17-0719fc8b2a9e>:3: batch (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.batch(batch_size)` (or `padded_batch(...)` if `dynamic_pad=True`).


In [18]:
################나머지는 거의 같음.###################
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [19]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

In [20]:
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [21]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [22]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

In [23]:
################여기가 조금 다름.###################
# Start populating the filename queue.
coord = tf.train.Coordinator() #연산 돌아가라 라는 시작. (tf.Session()처럼 시작의 의미인듯.)
threads = tf.train.start_queue_runners(sess=sess, coord=coord)
#Coordinator는 멀티쓰레드가 함께 종료될 수 있도록 도와주고, 예외처리를 할 수 있도록 제공하고 있다.
#QueueRunner는 동일한 큐안에서 tensor가 동작할 수 있도록 쓰레드를 생성하는데 도움을 준다.
#다시말해, 큰 데이터를 동시에 처리하기 위해 필요한 과정임. 위 두줄은 그냥 쓰고보는것. 같이다닌다.

W0813 13:11:13.644914  8112 deprecation.py:323] From <ipython-input-23-c1ec24fe29af>:4: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.


In [25]:
for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    #펌프질 해서 일정한 데이터 10개를 가져옴.
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    #가져온 데이터를 feed로 줌.
    if step % 400 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
#복잡해보이지만 이대로 따라하면 됨. x_batch , y_batch 를 씀에 주의.

0 Cost:  5.6423306 
Prediction:
 [[143.69073]
 [142.95587]
 [186.76698]
 [154.34761]
 [150.40602]
 [188.75351]
 [146.71654]
 [179.07744]
 [177.62047]
 [158.90056]]
400 Cost:  5.463255 
Prediction:
 [[143.72635]
 [142.96329]
 [186.67691]
 [154.18561]
 [150.52664]
 [188.73146]
 [146.46036]
 [179.29492]
 [177.54285]
 [158.85312]]
800 Cost:  5.3338 
Prediction:
 [[143.75812]
 [142.9661 ]
 [186.59958]
 [154.04465]
 [150.63414]
 [188.70924]
 [146.2342 ]
 [179.49141]
 [177.4778 ]
 [158.8152 ]]
1200 Cost:  5.2418604 
Prediction:
 [[143.78653]
 [142.96542]
 [186.53311]
 [153.92184]
 [150.73007]
 [188.68732]
 [146.03436]
 [179.66896]
 [177.42331]
 [158.78506]]
1600 Cost:  5.178151 
Prediction:
 [[143.8119 ]
 [142.96211]
 [186.47581]
 [153.81464]
 [150.81573]
 [188.66591]
 [145.85744]
 [179.8294 ]
 [177.37764]
 [158.76125]]
2000 Cost:  5.1356936 
Prediction:
 [[143.83461]
 [142.95686]
 [186.4264 ]
 [153.7209 ]
 [150.8923 ]
 [188.64525]
 [145.70065]
 [179.97441]
 [177.33931]
 [158.7426 ]]


In [26]:
coord.request_stop() #쓰레드를 멈추도록 요청함.
coord.join(threads) #threads 가 멈출때까지 기다림.(각 쓰레드의 과정이 멈출때까지임.)
#위에서 두줄을 반드시 썻으면, 아래의 두줄도 반드시 써줄것. (써주는게 좋을것이다.)

In [27]:
# Ask my score
print("Your score will be ", #내 점수 예측
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ", #친구들 점수 예측
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[188.02606]]
Other scores will be  [[176.93921]
 [175.94388]]


## 3. Logistic(Regression) Classifier
---

### 3-1) Sample Data

In [34]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

In [35]:
x_data = [[1, 2],
          [2, 3],
          [3, 1],
          [4, 3],
          [5, 3],
          [6, 2]]
y_data = [[0],
          [0],
          [0],
          [1],
          [1],
          [1]]

In [36]:
# placehold ers for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 2]) #shape에 주의!
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [37]:
W = tf.Variable(tf.random_normal([2, 1]), name='weight')
#x변수 2개, y변수 1개이므로 -> 벡터로 그냥 줘도 됨에 주목. random_normal은 차원을 input으로 받음.
b = tf.Variable(tf.random_normal([1]), name='bias')

In [38]:
# Hypothesis using sigmoid: tf.div(1., 1. + tf.exp(tf.matmul(X, W))) <- tf.div(분자,분모) 나누기함수.
hypothesis = tf.sigmoid(tf.matmul(X, W) + b) #<-- sigmoid를 쓰면 깔끔히 구현 가능.
#XW +b

In [39]:
# w = tf.Variable([3,1],dtype=tf.float32 , name = "weight") #이렇게하면 shape가 결정이 안됨. 괜히 random주는게 아님.
# b = tf.Variable([2],dtype = tf.float32 , name = 'error')
w = tf.Variable(tf.random_normal([3,1]), dtype = tf.float32 , name = 'weight')
b = tf.Variable(tf.random_normal([1]), dtype = tf.float32 , name = 'error')
#tf.Session().run(tf.random_normal([1]))

In [40]:
# Hypothesis using sigmoid: tf.div(1., 1. + tf.exp(tf.matmul(X, W)))
hypothesis = tf.sigmoid(tf.matmul(X, W) + b) #<-- sigmoid를 쓰면 깔끔히 구현 가능.
#XW +b

In [41]:
# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                       tf.log(1 - hypothesis))
# - 잊지말고,

In [42]:
train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)
#이 cost를 minimize를 해주면 됨. 또는 optimizer=tf.train.GradientDescentOptimizer() 로 놓고,
#그레디언트 백터 수정가능. 이미했음.

In [43]:
# Accuracy computation
# True if hypothesis>0.5 else False <---보통 이이렇다.
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
#casting을 하면 T=1 , F=0 이 된다. tf.cast(조건,타입) 잊지말기.
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))
#tf.equal(a,b)는 a,b가 같은지 다른지를 boolean 으로 반환하는 함수. 잊지말기.
#똑같은지를 보고, cast를 하면 T=1 , F=0이 나오고 , 이게 정확도를 간단하게 계산하게됨.

In [46]:
# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        #학습을 많이 시킨다는건 모형의 모수를 더욱더 참값으로 보낸다는 뜻.
        cost_val, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})
        if step % 2000 == 0:
            print(step, cost_val) #cost만 살펴보자.
    # Accuracy report <--- 학습된 모델을 가지고 예측을 봄.
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X: x_data, Y: y_data})
    #hypothesis가 0.5보다 작은지 큰지를 보자.
    print("\nHypothesis: \n", h, "\nCorrect (Y): \n", c, "\nAccuracy: ", a)
            

0 1.1910583
2000 0.31802496
4000 0.24405642
6000 0.19654042
8000 0.16415827
10000 0.1408933

Hypothesis: 
 [[0.02720624]
 [0.15376168]
 [0.28748438]
 [0.7894395 ]
 [0.94453937]
 [0.98184776]] 
Correct (Y): 
 [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 
Accuracy:  1.0


### 3-2) Real Data


In [47]:
import tensorflow as tf
import numpy as np
import pandas as pd
tf.set_random_seed(777)  # for reproducibility

In [48]:
#xy = np.loadtxt('/Users/82104/Desktop/data-03-diabetes.csv', delimiter=',', dtype=np.float32)
xy = pd.read_csv('/Users/82104/Desktop/data-03-diabetes.csv',dtype=np.float32,header=None)
#당노병 예측 실제 데이터.
x_data = xy.iloc[:,0:-1]
y_data = xy.iloc[:,[-1]]
#x_data = xy[:, 0:-1]
#y_data = xy[:, [-1]] #데이터 load하면됨.

In [49]:
print(x_data.shape, y_data.shape)

(759, 8) (759, 1)


In [50]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 8]) #shape에만 주의해서 정하면됨.
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [51]:
W = tf.Variable(tf.random_normal([8, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [52]:
# Hypothesis using sigmoid: tf.div(1., 1. + tf.exp(-tf.matmul(X, W)))
hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                       tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

In [53]:
# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [56]:
#Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        cost_val, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})
        if step % 2000 == 0:
            print(step, cost_val)

    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X: x_data, Y: y_data})
    print("\nHypothesis: \n", h, "\nCorrect (Y): \n", c, "\nAccuracy: ", a)
##76% 정확도를 나타냄을 알 수 있다.

0 1.0869305
2000 0.53223085
4000 0.50584364
6000 0.49252087
8000 0.48520464
10000 0.4808947

Hypothesis:  [[0.38944006]
 [0.924068  ]
 [0.2025939 ]
 [0.9515435 ]
 [0.13465053]
 [0.76387036]
 [0.9448555 ]
 [0.57261163]
 [0.258148  ]
 [0.543106  ]
 [0.7211889 ]
 [0.15649366]
 [0.2276884 ]
 [0.23791915]
 [0.7274986 ]
 [0.46039462]
 [0.72734994]
 [0.8721862 ]
 [0.8336769 ]
 [0.60514325]
 [0.67129534]
 [0.10478103]
 [0.62525797]
 [0.6659905 ]
 [0.36418462]
 [0.9353281 ]
 [0.53322005]
 [0.6568461 ]
 [0.6885811 ]
 [0.43789077]
 [0.9513699 ]
 [0.87548643]
 [0.5438442 ]
 [0.8193344 ]
 [0.34039333]
 [0.6154221 ]
 [0.82387054]
 [0.56001   ]
 [0.46810448]
 [0.35712463]
 [0.81579024]
 [0.14812586]
 [0.39732477]
 [0.04294527]
 [0.58536077]
 [0.92576575]
 [0.68051153]
 [0.70123816]
 [0.93937993]
 [0.9341443 ]
 [0.93402016]
 [0.23281625]
 [0.3381741 ]
 [0.96163726]
 [0.20358321]
 [0.5059605 ]
 [0.11043137]
 [0.7127359 ]
 [0.8839052 ]
 [0.49543756]
 [0.94834685]
 [0.7189176 ]
 [0.6589628 ]
 [0.8406136 

In [57]:
#CSV reading using tf.decode_csv (Queue)
#Try other classificiation data from Kaggle (케글가기)

## 4. Sources
---

- [Main site](https://hunkim.github.io/ml/)
- [Github](https://hunkim.github.io/ml/)