# [Chapter 8 ~ 9 ]

*KU LeeDongGyu*

## 1. Tensor Manipulation
---

In [1]:
# 참고 사이트 : https://www.tensorflow.org/api_guides/python/array_ops 

In [2]:
import tensorflow as tf
import numpy as np
import pprint
tf.set_random_seed(777)  # for reproducibility

### 1-1) pprint

In [3]:
# pprint 과 print의 비교에 대한 설명.
#https://pythonkim.tistory.com/91
# numbers = [[1,2,3],[4,5],[6,7,8,9]]
# print(numbers)
# print(*numbers) #와우!
# print(*numbers,sep='\n')

In [4]:
pp = pprint.PrettyPrinter(indent=4)
#indent는 들여쓰기. 그 칸수를 4칸만큼.
#pp라는 변수에 늘 pprint문법을 적용하고 시행시킨다는 뜻.

In [5]:
sess = tf.InteractiveSession()
#sess의 전달 없이도 tf문의 eval을 실행시킬수 있게 됨.
#참고 : https://tensorflowkorea.gitbooks.io/tensorflow-kr/content/g3doc/api_docs/python/client.html

In [6]:
#비교.
# a = tf.constant(5.0)
# b = tf.constant(6.0)
# c = a * b
# sess = tf.Session()
# sess.run(c) #c.eval() 은 실행불가.
##############
# sess = tf.InteractiveSession()
# a = tf.constant(5.0)
# b = tf.constant(6.0)
# c = a * b
# 'sess'의 전달없이도 'c.eval()'를 실행할 수 있다.
# print(c.eval()) #run을 안쓰고도 쉽게 실행가능.
# sess.close()  #닫을땐 close를 사용해서 끝.

### 1-2) simple array

In [7]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
#print(t) 차이점을 봐라. pprint가 더 이쁨.
print(t.ndim) # rank #1차원
print(t.shape) # shape #7개
print(t[0], t[1], t[-1]) #index를 뽑음.
print(t[2:5], t[4:-1]) #slice하는 방법.
print(t[:2], t[3:])

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


### 1-3) 2D array

In [8]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]]) #1차원 array 섞어놓은거.
pp.pprint(t)
print(t.ndim) # rank 쉽게 계산가능.
print(t.shape) # shape

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


### 1-4) shape, rank, axis

In [9]:
t = tf.constant([1,2,3,4])
tf.shape(t).eval() #eval을 쓰는것만으로 값을 출력할 수 있음.

array([4])

In [10]:
t = tf.constant([[1,2],
                 [3,4]])
#rank는 괄호의 개수, shape 은 ,개수 +1 임
#shape의 원소의 개수가 바로 rank 값임.
tf.shape(t).eval()

array([2, 2])

In [20]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval()

array([1, 2, 3, 4])

In [12]:
[ #Axis=0 (0부터 시작해서 안쪽으로 들어간다.)
    [ #Axis=1
        [ #Axis = 2
            [1,2,3,4], #Axis =3 이자 Axis = -1 (제일 안쪽의 있는 값)
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20],
            [21,22,23,24]
        ]
    ]
]
#이쁘게 표현하는 방법임.
#Axis의 개수는 rank임.
#Axis는 0부터 시작하며, 가장 안쪽에 있는 값이 가장 큰 값.

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

### 1-5) matmul vs multiply

In [14]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])

In [15]:
tf.matmul(matrix1, matrix2).eval()

array([[12.]], dtype=float32)

In [16]:
(matrix1*matrix2).eval() #요소별 곱.

array([[6., 6.],
       [6., 6.]], dtype=float32)

### 1-6) watch out broadcasting

In [17]:
#broadcasting이란 , shape이 달라도 연산이 가능하게끔 해주는 기능. (유연하게 계산함)
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
(matrix1+matrix2).eval()

array([[5., 5.],
       [5., 5.]], dtype=float32)

In [18]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1+matrix2).eval()

array([[5., 5.]], dtype=float32)

In [21]:
matrix1 = tf.constant([[1., 2.]]) #이렇게 행벡터랑 열벡터도 계산이 됨.
matrix2 = tf.constant([[3.], [4.]])
(matrix1+matrix2).eval()
(matrix2+matrix1).eval() #되도록 정확하게 사용하기.

array([[4., 5.],
       [5., 6.]], dtype=float32)

### 1-7) random values for variable initializations

In [22]:
tf.random_normal([3]).eval()
tf.random_uniform([2]).eval()
tf.random_uniform([2, 3]).eval()

array([[0.44877207, 0.67982817, 0.19171011],
       [0.56397057, 0.24419773, 0.01089573]], dtype=float32)

### 1-8) reduce mean & sum

In [24]:
tf.reduce_mean([1, 2], axis=0).eval()
#주의!!. int인지 float인지에 따라서 결과값이 다르게나옴. 1.5가 아니다!

x = [[1., 2.],
     [3., 4.]]

In [26]:
tf.reduce_mean(x).eval()
#tf.reduce_mean(x) 는 tensor 이름이 나옴.

2.5

In [27]:
tf.reduce_mean(x, axis=0).eval()

array([2., 3.], dtype=float32)

In [28]:
tf.reduce_mean(x, axis=1).eval()

array([1.5, 3.5], dtype=float32)

In [29]:
tf.reduce_mean(x, axis=-1).eval() #가장 안쪽에 있는것을 평균내어라.(자주쓴다)

array([1.5, 3.5], dtype=float32)

In [31]:
tf.reduce_sum(x).eval()

10.0

In [32]:
tf.reduce_sum(x, axis=0).eval()

array([4., 6.], dtype=float32)

In [33]:
tf.reduce_sum(x, axis=-1).eval()

array([3., 7.], dtype=float32)

In [34]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval() #많이 쓰는 코드.

5.0

### 1-9) argmax with axis

In [35]:
x = [[0, 1, 2],
     [2, 1, 0]]

In [36]:
tf.argmax(x, axis=0).eval()  #위치를 구한다.

array([1, 0, 0], dtype=int64)

In [37]:
tf.argmax(x, axis=1).eval()

array([2, 0], dtype=int64)

In [38]:
tf.argmax(x, axis=-1).eval()

array([2, 0], dtype=int64)

### 1-10) reshape , squeeze , expand_dims

In [39]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],

              [[6, 7, 8],
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [40]:
tf.reshape(t, shape=[-1, 3]).eval() #보통 맨 마지막 값은 그대로 가져가고, 나머지 차원을 조절하기에
                                    #데이터의 의미가 크게 변질되진 않는다.

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [41]:
tf.reshape(t, shape=[-1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [42]:
tf.squeeze([[0], [1], [2]]).eval() #값을 펴줌. 와우! numpy의 flatten()과 같음.

array([0, 1, 2])

In [43]:
tf.expand_dims([0, 1, 2],1).eval() #역시나 차원을 바꿈.

array([[0],
       [1],
       [2]])

### 1-11) one_hot

In [44]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval() #주의! rank가 2에서 3으로 자동으로 됨.

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [45]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval() #반드시 one-hot은 reshape와 따라다닌다!
#depth는 필수옵션임.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [46]:
#만약 y는 벡터이고, tf.one_hot(y)하면, 벡터가 행렬로 바뀌면서 one-hot되므로 상관없음.
#예)
# y = [1,2,3,4]
# tf.one_hot(y,depth=4).eval() 이렇게 design matrix가 만들어진다.

### 1-12) casting

In [47]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4])

In [48]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()
#tf.cast([True, False, 1 == 1, 0 == 1]).eval() #얘는 실행이안됨. dtype옵션은 필수기때문.
#True False를 int로 바꾸면 1과 0으로 출력된다!!

array([1, 0, 1, 0])

### 1-13) stack

In [49]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

In [50]:
# Pack along first dim.
tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [51]:
tf.stack([x, y, z], axis=1).eval() #축을 바꿈으로써 쌓는 방법을 다르게 할 수 있다.

array([[1, 2, 3],
       [4, 5, 6]])

### 1-14) ones like & zeros like

In [52]:
x = [[0, 1, 2],
     [2, 1, 0]]

In [53]:
tf.ones_like(x).eval() #1로 채워진 tense를 x와 같은 shape으로 만들어줌.

array([[1, 1, 1],
       [1, 1, 1]])

In [54]:
tf.zeros_like(x).eval() #얘는 0으로 채워짐.

array([[0, 0, 0],
       [0, 0, 0]])

### 1-15) zip

In [55]:
#매우유용하다. 꼭기억
for x, y in zip([1, 2, 3], [4, 5, 6]): #묶어서 한방에 처리 자주쓴다.
    print(x, y)

1 4
2 5
3 6


In [56]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9


### 1-16) transpose

In [57]:
# 1. shape 결정 : https://superelement.tistory.com/18 이글을 참고하면 더 도움이 된다.
# 2. 값 결정 : i,j,k 각 원소를 바뀌는 형태(5가지중 하나) 로 1-1 mapping시키면 됨.

In [58]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])

In [59]:
pp.pprint(t.shape)
pp.pprint(t)

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [60]:
t1 = tf.transpose(t, perm= [1, 0, 2]) #변경할 축을 지정함. 옵션은 순열일뿐.
#참고) 기존의 형태 perm은 0,1,2였고 1,0,2로 바꾸라는 의미는
# 0 -> 두번째로, 1 -> 첫번째로, 2 -> 두번째로 라는 의미이다.
# 3차원이면, 3! - 1 =5 개의 perm 가짓수가 존재.
#여기까지가 perm (즉, shape)을 결정짓는 설명.
#[0,1,2]면 , 0에 해당하는 부분이 제일 겉 list임.
#그렇기에, [0,2,1]을 perm 옵션으로 주면 큰 list 형태는 유지하고, 각 행렬이 T됨.

In [61]:
pp.pprint(sess.run(t1).shape)
pp.pprint(sess.run(t1))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])


In [62]:
t = tf.transpose(t1, [1, 0, 2])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t)) #다시 원래대로 돌아옴.

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [63]:
t2 = tf.transpose(t, [1, 2, 0])
pp.pprint(sess.run(t2).shape)
pp.pprint(sess.run(t2))

(2, 3, 2)
array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])


In [64]:
t = tf.transpose(t2, [2, 0, 1])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


## 2. NN(Neural Net) for XOR
---

### 2-1) Wrong coding

In [65]:
# Lab 9 XOR 
# 참고) XOR 기호: 동그라미 안에 더하기

In [66]:
import tensorflow as tf
import numpy as np

In [67]:
tf.set_random_seed(777)  # for reproducibility

x_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)

In [68]:
X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

W = tf.Variable(tf.random_normal([2, 1]), name="weight")
b = tf.Variable(tf.random_normal([1]), name="bias")

# Hypothesis using sigmoid: tf.div(1., 1. + tf.exp(tf.matmul(X, W)))
hypothesis = tf.sigmoid(tf.matmul(X, W) + b) # 로지스틱 회귀를 사용해서 한다.
                                             # 0과 1의 값으로 나타나있기 때문.

Instructions for updating:
Colocations handled automatically by placer.


In [69]:
# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [70]:
# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32) #cast를 통해 숫자형태로 바꿈.
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [72]:
# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        _, cost_val, w_val = sess.run(
                  [train, cost, W], feed_dict={X: x_data, Y: y_data}
        )
        if step % 1000 == 0:
            print(step, cost_val, w_val)

    # Accuracy report
    h, c, a = sess.run(
              [hypothesis, predicted, accuracy], feed_dict={X: x_data, Y: y_data}
    )
    print("\nHypothesis: ", h, "\nCorrect: ", c, "\nAccuracy: ", a)

#잘 안된다. accuracy는 0.5임.
#이게 되게하는 방법은 Neural Net을 사용하는 거임. (2단으로 층수조절)

0 0.7911055 [[ 1.4042796 ]
 [-0.04965878]]
1000 0.6931666 [[0.01836386]
 [0.01551328]]
2000 0.6931472 [[0.00033516]
 [0.00032976]]
3000 0.6931472 [[6.5187205e-06]
 [6.5113195e-06]]
4000 0.6931472 [[1.3951873e-07]
 [1.3956875e-07]]
5000 0.6931472 [[8.885474e-08]
 [8.890476e-08]]
6000 0.6931472 [[8.885474e-08]
 [8.890476e-08]]
7000 0.6931472 [[8.885474e-08]
 [8.890476e-08]]
8000 0.6931472 [[8.885474e-08]
 [8.890476e-08]]
9000 0.6931472 [[8.885474e-08]
 [8.890476e-08]]
10000 0.6931472 [[8.885474e-08]
 [8.890476e-08]]

Hypothesis:  [[0.5]
 [0.5]
 [0.5]
 [0.5]] 
Correct:  [[0.]
 [0.]
 [0.]
 [0.]] 
Accuracy:  0.5


### 2-2) Right coding

In [73]:
# Lab 9 XOR
import tensorflow as tf
import numpy as np

In [74]:
tf.set_random_seed(777)  # for reproducibility

x_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)

In [75]:
X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

In [76]:
W1 = tf.Variable(tf.random_normal([2, 2]), name='weight1') #in은 정해짐. 그러나 그냥 out을 2로함.
b1 = tf.Variable(tf.random_normal([2]), name='bias1') #여기도 2임.
layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)

In [77]:
W2 = tf.Variable(tf.random_normal([2, 1]), name='weight2') #위에서 out이 2었기에, 2를 in으로 받음.
                                                           # y의 출력은 1로 정해짐.
b2 = tf.Variable(tf.random_normal([1]), name='bias2')
hypothesis = tf.sigmoid(tf.matmul(layer1, W2) + b2) # 층이 하나 더생김
#주의할 점 ! weight의 크기를 잘 정해줘야함.
# 2층을 쌓는 이유는 내생각엔 분류 직선을 긋기위해 2차원을 3차원으로 접목시켜서
# 선이아닌 평면, 하이퍼평면으로 분류를 한다는것과 같은 맥락인 것 같음.
# 이로써 deep을 얼마나 할지가 해결되는거 같음.
# Q) wide는 어떻게 정할까??

In [78]:
# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [79]:
# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [80]:
# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        _, cost_val = sess.run([train, cost], feed_dict={X: x_data, Y: y_data})
        if step % 1000 == 0:
            print(step, cost_val)

    # Accuracy report
    h, p, a = sess.run(
        [hypothesis, predicted, accuracy], feed_dict={X: x_data, Y: y_data}
    )

    print(f"\nHypothesis:\n{h} \nPredicted:\n{p} \nAccuracy:\n{a}")

#1단에서 2단으로 바꿧을 뿐인데, 정확도는 100%로 진화함.
#hypothesis 의 값을 올리려면, 더 deep하고 wide하게 만들면 됨.

0 1.186164
1000 0.67613363
2000 0.6120584
3000 0.53245074
4000 0.33908463
5000 0.14787745
6000 0.08682288
7000 0.060235545
8000 0.045749314
9000 0.036735613
10000 0.030621253

Hypothesis:
[[0.02703822]
 [0.9644734 ]
 [0.9657304 ]
 [0.02372456]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0


### 2-3) More precise code

In [81]:
#더  deep하고 wide하게
# Lab 9 XOR
import tensorflow as tf
import numpy as np

In [82]:
tf.set_random_seed(777)  # for reproducibility

x_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)

In [83]:
X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

In [84]:
W1 = tf.Variable(tf.random_normal([2, 10]), name='weight1') #좀 과하지만 10개로 wide하게 설정.
b1 = tf.Variable(tf.random_normal([10]), name='bias1') #역시나 여기도 바꿨다는거 인지!
layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)
#이렇게 wide하게 하면 값이 더 정밀해짐.

W2 = tf.Variable(tf.random_normal([10, 10]), name='weight2')
b2 = tf.Variable(tf.random_normal([10]), name='bias2')
layer2 = tf.sigmoid(tf.matmul(layer1, W2) + b2)

W3 = tf.Variable(tf.random_normal([10, 10]), name='weight3')
b3 = tf.Variable(tf.random_normal([10]), name='bias3')
layer3 = tf.sigmoid(tf.matmul(layer2, W3) + b3)

W4 = tf.Variable(tf.random_normal([10, 1]), name='weight4')
b4 = tf.Variable(tf.random_normal([1]), name='bias4')
hypothesis = tf.sigmoid(tf.matmul(layer3, W4) + b4) #이렇게 4번째까지 deep하게 만들 수도 있음.

#### -> wide하고 deep하게 만들수 있음.

In [85]:
# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [86]:
# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [87]:
# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        _, cost_val = sess.run([train, cost], feed_dict={X: x_data, Y: y_data})
        if step % 1000 == 0:
            print(step, cost_val)

    # Accuracy report
    h, c, a = sess.run(
        [hypothesis, predicted, accuracy], feed_dict={X: x_data, Y: y_data}
    )
    print("\nHypothesis: ", h, "\nCorrect: ", c, "\nAccuracy: ", a)
# 더 정밀해졌다.

0 0.95644665
1000 0.4856874
2000 0.037384026
3000 0.010779493
4000 0.0056470633
5000 0.0036962284
6000 0.0027049019
7000 0.0021148457
8000 0.0017270744
9000 0.0014543261
10000 0.0012528277

Hypothesis:  [[7.5820088e-04]
 [9.9926102e-01]
 [9.9844635e-01]
 [1.9562542e-03]] 
Correct:  [[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:  1.0


## 3. Tensorboard for XOR
---

In [88]:
#TensorBoard

#tensorbard 는 deep하고 wide하게 만들 때, 그 진행과정을 만드는 유용한 방법임. (그래프를 그림)
#step에 따라서 loss가 어떻게 변화하는지를 볼 수 있음.
# 이전에는 단순히 print로 본 것에서 upgrade 한 것임.

#아래의 5개의 step을 따라간다면, 멋진 그래프를 그릴 수 있음.

In [89]:
############ 요약 ############

#### 1 From TF graph, decide which tensors you want to log
#### w2_hist = tf.summary.histogram('weights2',w2)
#### cost_summ = tf.summary.scalar('cost',cost)

#### 2. Merge all summaries
#### summary = tf.summary.merge_all()

#### 3. Create writer and add graph
#### writer = tf.summary.FileWriter('./logs') #full path 입력해보기. // 어느위치에 경로를 적을껀지
#### writer.add_graph(sess.graph) #같이 쓰면 됨.

#### 4. Run summary merge and add_summary #summary자체도 tense이기 때문에 실행시켜야함.
#### s, _ = sess.run([summary , optimizer],feed_dict=feed_dict)
#### writer.add_summary(s , global_step=global_step) #실제로 파일에 기록하는 함수.

#### 5. Launch TensorBoard #터미널 가서, 정해진 디렉토리를 '=' 오른쪽에 넣기
#### tensorboard --logdir=./logs     #"--logdir=./logs" 띄어쓰기 없이 해보기

In [90]:
############ 순서 시작 ############

# 1. 열심히 코드를 실행한다. (import부터 for문 다 돌리는거까지)
# 2. 터미널에 [[[ tensorboard --logdir=./logs ]]] 를 실행한다.
#### 이 의미는 , [[[ C:\Users\82104\PycharmProjects\untitled\logs]]] 를 실행하는것. ###
# 혹은, [[[ tensorboard --logdir=path/to/log-directory]]] 를 실행한다.
# 이때, writer = tf.summary.FileWriter("./logs/xor_logs") 와 같이 되어있을 것이다.
# 참고 사이트 :  https://tensorflowkorea.gitbooks.io/tensorflow-kr/content/g3doc/how_tos/summaries_and_tensorboard/

# 3. 인터넷에 가서 [[[ localhost:6006 ]]] 를 입력하고 확인한다.
# 4. 터미널을 종료하려면 [[[ ctrl+c ]]]를 누른다.

# 5. 만약 여러개를 실행하고 싶으면,
# 5-1 )
# 코드 중 [[[ writer = tf.summary.FileWriter("./logs/xor_logs") ]]] 로 바꾼다.
# 또한 다르게 돌릴 목적에 맞게 코드를 수정한다. (ex:  learning_rate = 0.1)
# 터미널에 [[[  tensorboard --logdir=./logs/xor_logs  ]]] 하고 데이터 돌리고 터미널 종료.
# 5-2)
# 코드 중 [[[ writer = tf.summary.FileWriter("./logs/xor_logs_r0_01")  ]]] 로 바꾼다.
# 또한 다르게 돌릴 목적에 맞게 코드를 수정한다. (ex:  learning_rate = 0.001)
# 터미널에 [[[  tensorboard --logdir=./logs/xor_logs_r0_01 ]]] 하고 데이터 돌리고 터미널 종료.
# 5-3)
# 그리고 최종적으로 [[[ tensorboard --logdir=./logs  ]]] 를 실행
# 이러면 동시에 볼 수 있게 된다.

#6. 만약 서버를 할당받고 싶으면,
# 터미널에 [[[ ssh -L 7007:121.0.0.0:6006 donggyu@server.com ]]] 이라 하면,
# 6006번에 해당하는게 7007번으로 donggyu이름을 지닌채 할당받음.
# 이후 , 인터넷 주소창에 [[[ localhost:7007  ]]] 을 입력한다.

############ 순서 끝 ############

In [91]:
#Tensorboard Tip)
# 1. Scalars
# smoothing : 이동평균을 취해서 부드럽게 하라는것. 0값을 넣으면, 원데이터 그대로를보여줌.
# 나머지는 직관적으로 볼 수 있음.

#2. Graphs
#우리가 어떻게 코딩을 했고, 어떤 알고리즘을 갖는지 시각적으로 표현하는 파트.
#with문을 쓰고, name_scope를 쓰는 이유는 이 파트에서 깔끔하게 보기 위함.
#그래프들을 더블클릭해서 세부 계산 과정을 볼 수 있음. 확인 해보기.

#3. Histograms
# y축은 step, x축은 벡터들의 원소가 가지는 각 값에 대한 분포임.
# 즉, step 이 경과함에 따라 어떻게 값이 변화하는지를 볼 수 있음.

In [92]:
# Lab 9 XOR
import tensorflow as tf
import numpy as np

In [94]:
tf.set_random_seed(777)  # for reproducibility

In [99]:
tf.set_random_seed(777)  # for reproducibility

x_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)

X = tf.placeholder(tf.float32, [None, 2], name="x") #아래에서도 마찬가지지만, 이름을 정하자.
Y = tf.placeholder(tf.float32, [None, 1], name="y")

In [100]:
#Add scope for better graph hierarchy
#그래프를 그릴때, layer1과 layer2를 보기 좋게 만들 수 있음.
#아래처럼 하는걸 습관화하자. (tf.name_scope는 tensorboard에서 그래프 구성을 깔끔하게 볼 수 있도록 도와줌.)

In [101]:
with tf.name_scope("Layer1"): #Layer1은 이름정한것.
    W1 = tf.Variable(tf.random_normal([2, 2]), name="weight_1")
    b1 = tf.Variable(tf.random_normal([2]), name="bias_1")
    layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)

    tf.summary.histogram("W1", W1) #tf.summary 매서드를 잊지말기.
    tf.summary.histogram("b1", b1)
    tf.summary.histogram("Layer1", layer1)

In [102]:
with tf.name_scope("Layer2"):
    W2 = tf.Variable(tf.random_normal([2, 1]), name="weight_2")
    b2 = tf.Variable(tf.random_normal([1]), name="bias_2")
    hypothesis = tf.sigmoid(tf.matmul(layer1, W2) + b2)

    tf.summary.histogram("W2", W2)
    tf.summary.histogram("b2", b2)
    tf.summary.histogram("Hypothesis", hypothesis)

In [103]:
# cost/loss function
with tf.name_scope("Cost"): #cost와 train 또한 그래프로 만들어 버린다. 습관화.
    cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))
    tf.summary.scalar("Cost", cost) #cost는 scalar이기에, histogram 문법을 쓰지 않는다.

with tf.name_scope("Train"):
    train = tf.train.AdamOptimizer(learning_rate=0.01).minimize(cost)

In [104]:
#AdamOptimizer 란,
# Momentum(모멘텀) + RMSprop(알엠에스프롭) 기법이 혼합된 최적화기법
# (관성 효과 + 지수이동평균 의 혼합이다.) 이런게 있다 하고 넘어가기.
#다음의 사이트를 참고하면 Optimizer들에 대한 이야기를 자세히 살필 수 있다.
# https://twinw.tistory.com/247

In [105]:
# Accuracy computation
# True if hypothesis>0.5 else False

predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))
tf.summary.scalar("accuracy", accuracy)  #accuracy 또한 scalar이기에, histogram 문법을 쓰지 않는다.

<tf.Tensor 'accuracy:0' shape=() dtype=string>

In [106]:
# Launch graph
with tf.Session() as sess:
    # tensorboard --logdir=./logs/xor_logs_r0_01 였음.
    merged_summary = tf.summary.merge_all()  #요약 할것을 다합쳐버리고,
    writer = tf.summary.FileWriter("./logs/xor_logs_r0_01") # 이 경로에 정보를 넣는다.
    # 이의미는 , C:\Users\82104\PycharmProjects\untitled\logs\xor_logs_r0_01 를 실행하는것.
    writer.add_graph(sess.graph)  # Show the graph  & Add graph in the tensorboard

    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        _, summary, cost_val = sess.run(
            [train, merged_summary, cost], feed_dict={X: x_data, Y: y_data}  #train 시키면서 요약된 값들도 얻어내고,
        )
        writer.add_summary(summary, global_step=step) #요약본을 step이 진행될수록 계속 합쳐버리면서 누적시킨다. 이때 writer변수는
                                                      #경로에 해당하는 변수이고, 데이터가 저장되는 공간 (위에서 정의함.)
        #add_summary(summary,step) 와 add_graph(sess.graph)를 잊지 말기.

        if step % 1000 == 0:
            print(step, cost_val)

    # Accuracy report
    h, p, a = sess.run(
        [hypothesis, predicted, accuracy], feed_dict={X: x_data, Y: y_data}
    )

    print(f"\nHypothesis:\n{h} \nPredicted:\n{p} \nAccuracy:\n{a}")

0 0.69531196
1000 0.025503881
2000 0.007181977
3000 0.003139354
4000 0.0016090515
5000 0.00088958116
6000 0.0005120914
7000 0.00030163047
8000 0.00018000745
9000 0.00010830755
10000 6.5477856e-05

Hypothesis:
[[5.9306622e-05]
 [9.9993449e-01]
 [9.9993807e-01]
 [7.4893236e-05]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0


## 4. Sources
---

- [Main site](https://hunkim.github.io/ml/)
- [Github](https://hunkim.github.io/ml/)