# [1-1 NN]

*KU LeeDongGyu*

### Note :

This code was used during the workshop at Kyungpook National University. <br>
Also, the content of this material is what I learned while moving Pycham to Jupyter.

Reference : TensorFlow 2.1 Quick Start Guide (by Holdroyd)

### Install

In [2]:
pip install tensorflow

  Using cached https://files.pythonhosted.org/packages/34/d5/ce8c17971067c0184c9045112b755be5461d5ce5253ef65a367e1298d7c5/tensorflow-2.1.0-cp37-cp37m-win_amd64.whl
  Using cached https://files.pythonhosted.org/packages/30/c6/286db43e2d0d4b89d328a222365c7a253a99a24067812253f0d4f8eb0f1c/protobuf-3.11.2-cp37-cp37m-win_amd64.whl
  Using cached https://files.pythonhosted.org/packages/61/51/046cbc61c7607e5ecead6ff1a9453fba5e7e47a5ea8d608cc7036586a5ef/scipy-1.4.1-cp37-cp37m-win_amd64.whl
  Using cached https://files.pythonhosted.org/packages/28/6a/8c1f62c37212d9fc441a7e26736df51ce6f0e38455816445471f10da4f0a/Keras_Preprocessing-1.1.0-py2.py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/8b/14/ab1501cfff78b88d7368659b227c603d7599dd25226ff682c71334e78aed/grpcio-1.26.0-cp37-cp37m-win_amd64.whl
Processing c:\users\82104\appdata\local\pip\cache\wheels\5c\2e\7e\a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd\gast-0.2.2-cp37-none-any.whl
Processing c:\users\82104\appdata\loca

ERROR: tensorboard 2.1.0 has requirement setuptools>=41.0.0, but you'll have setuptools 40.8.0 which is incompatible.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [1]:
import tensorflow as tf

In [4]:
tf.__version__

'2.1.0'

## 1. Keras Sequential Model (1)
---

In [2]:
(train_x, train_y), (test_x,test_y) = tf.keras.datasets.mnist.load_data()

In [16]:
train_x

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [17]:
epochs = 10 ; batch_size=32 # 데이터 전체 훑는걸 10번반복, 데이터를 32개씩 적용시켜 모수갱신 

In [18]:
train_x,test_x = tf.cast(train_x/255.0,tf.float32), tf.cast(test_x/255.0, tf.float32)
#255로 나누는 이유는 타입을 float32로 했기 때문임. 입력값을 0~1사이의 소수로 받아야함.

In [83]:
train_x
# 주의할것은 tf.cast 는 모델을 Sequential() 로 정의할때만 사용한다!!!!!

<tf.Tensor: shape=(60000, 28, 28), dtype=float32, numpy=
array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0

In [19]:
train_y , test_y = tf.cast(train_y , tf.int64) , tf.cast(test_y , tf.int64)

In [21]:
model1 = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(), #먼저 펼쳐놓고(초기값 설정과 같은)
    tf.keras.layers.Dense(512,activation=tf.nn.relu), #노드개수 512개로 출력, act.ftn은 relu
    tf.keras.layers.Dropout(0.2), # 20%개를 0으로 둠. (80%만 사용)
    tf.keras.layers.Dense(10,activation=tf.nn.softmax) #10개로 분류하기 위해 softmax사용
])

In [22]:
optimiser = tf.keras.optimizers.Adam() #Adam 최적화. defalut 값을 주고 사용함.
# Adam클래스내에서 초기값을 따로 주고 사용할 수도 있음.

In [25]:
model1.compile(optimizer = optimiser,loss='sparse_categorical_crossentropy',
              metrics = ['accuracy'])
# sparse_categorical_crossentropy 는 one-hot encdoing 없이 바로 접근 가능
# categorical_crossentropy는 one-hot encdoing이 되어있는 경우 사용 가능.
# 정확도를 측도로 사용 (꼭 리스트로 표현할 것.)

In [26]:
model1.fit(train_x, train_y, batch_size=batch_size, epochs=epochs)
# model 학습

Train on 60000 samples
Epoch 1/10
60000/60000 [==============================] - 12s 197us/sample - loss: 0.2183 - accuracy: 0.9348
Epoch 2/10
60000/60000 [==============================] - 11s 176us/sample - loss: 0.0972 - accuracy: 0.9705
Epoch 3/10
60000/60000 [==============================] - 10s 173us/sample - loss: 0.0676 - accuracy: 0.9787
Epoch 4/10
60000/60000 [==============================] - 10s 172us/sample - loss: 0.0522 - accuracy: 0.9832
Epoch 5/10
60000/60000 [==============================] - 11s 179us/sample - loss: 0.0435 - accuracy: 0.9852
Epoch 6/10
60000/60000 [==============================] - 11s 178us/sample - loss: 0.0358 - accuracy: 0.9883
Epoch 7/10
60000/60000 [==============================] - 10s 172us/sample - loss: 0.0314 - accuracy: 0.9896
Epoch 8/10
60000/60000 [==============================] - 11s 182us/sample - loss: 0.0263 - accuracy: 0.9911
Epoch 9/10
60000/60000 [==============================] - 12s 193us/sample - loss: 0.0258 - accuracy: 0.9

In [27]:
model1.evaluate(test_x,test_y)
#모형을 평가하고싶으면, 이렇게 입력

10000/10000 [==============================] - 1s 112us/sample - loss: 0.0663 - accuracy: 0.9835


[0.06625128462110734, 0.9835]

## 2. Keras Sequential Model (2)
---

In [84]:
(train_x,train_y), (test_x, test_y) = tf.keras.datasets.mnist.load_data()

In [85]:
train_x, test_x = tf.cast(train_x/255.0, tf.float32), tf.cast(test_x/255.0, tf.float32)
train_y, test_y = tf.cast(train_y,tf.int64),tf.cast(test_y,tf.int64)

In [35]:
epochs = 3 ; batch_size = 32  # epoch 를 3번만 학습해보자.

In [31]:
model2 = tf.keras.models.Sequential()

In [33]:
model2.add(tf.keras.layers.Flatten())
model2.add(tf.keras.layers.Dense(512,activation='relu'))
model2.add(tf.keras.layers.Dropout(0.2))
model2.add(tf.keras.layers.Dense(10,activation=tf.nn.softmax))

# add함수를 통해 층을 계속 쌓아 나가는 중.
# 간단한 문제를 풀고자 할 때 위처럼 구현하면 편하다.

# 참고로, classification을 진행할 때는 데이터가 balanced data여야 함.
# 이에 대해 이미지 데이터는 GAN이 performance가 효과적이라고 함.

In [43]:
model2.compile(optimizer=tf.keras.optimizers.Adam(), loss='sparse_categorical_crossentropy',
              metrics = ['accuracy'])

In [36]:
model2.fit(train_x,train_y,batch_size=batch_size,epochs=epochs)

Train on 60000 samples
Epoch 1/3
60000/60000 [==============================] - 13s 216us/sample - loss: 0.4441 - accuracy: 0.8642
Epoch 2/3
60000/60000 [==============================] - 12s 193us/sample - loss: 0.1452 - accuracy: 0.9589
Epoch 3/3
60000/60000 [==============================] - 11s 191us/sample - loss: 0.1039 - accuracy: 0.9708


In [37]:
model2.evaluate(test_x,test_y)

10000/10000 [==============================] - 1s 119us/sample - loss: 0.0916 - accuracy: 0.9742


[0.09164073554351926, 0.9742]

## 3. Keras Functional API
---

In [38]:
# keras를 사용할 것이면, 이 방법을 눈여겨 보는것이 좋다.
# api는 sequential 버전이 있고, functional 버전이 있음.

In [5]:
import tensorflow as tf

In [6]:
(train_x,train_y) , (test_x,test_y) = tf.keras.datasets.mnist.load_data()

In [7]:
train_x.shape

(60000, 28, 28)

In [11]:
train_y.shape

(60000,)

In [62]:
train_x , test_x = train_x / 255.0 , test_x / 255.0
# tf.cast를 쓰면 작동이 안됨! 타입이 다름.
# tf.cast 는 모델을 Sequential() 로 정의할때만 사용!!
epochs = 3

In [50]:
inputs = tf.keras.Input(shape=(28,28))
# placeholder를 만든다. (여름방학에 공부한 개념)

In [52]:
x = tf.keras.layers.Flatten()(inputs) #마치 함수구조로 쌓아가주면 됨.
x = tf.keras.layers.Dense(512, activation='relu',name='d1')(x) #층 이름도 설정 가능.
x = tf.keras.layers.Dropout(0.2)(x)
predictions = tf.keras.layers.Dense(10,activation=tf.nn.softmax, name='d2')(x)

In [53]:
model3 = tf.keras.Model(inputs=inputs,outputs=predictions) # models라는 함수가 있고,
# Model 이라는 class가 있음 //  사용법은 완전히 같음.
# tf.keras.models.Model == tf.keras.Model

# 이런 방식으로 모델을 만들어버린다.

In [54]:
model3.summary() #이렇게 요약해서도 볼 수 있음.
# paramters 계산은 절편까지 계산됨.
# 즉, 784 * 512 + 512 = 401920 /// 512 * 10 + 10 = 5130 임.

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 28, 28)]          0         
_________________________________________________________________
flatten_6 (Flatten)          (None, 784)               0         
_________________________________________________________________
d1 (Dense)                   (None, 512)               401920    
_________________________________________________________________
dropout_3 (Dropout)          (None, 512)               0         
_________________________________________________________________
d2 (Dense)                   (None, 10)                5130      
Total params: 407,050
Trainable params: 407,050
Non-trainable params: 0
_________________________________________________________________


In [57]:
optimiser = tf.keras.optimizers.Adam()

In [59]:
model3.compile(optimizer = optimiser , loss = 'sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [63]:
model3.fit(train_x,train_y,batch_size=32,epochs=epochs)

Train on 60000 samples
Epoch 1/3
60000/60000 [==============================] - 11s 186us/sample - loss: 0.1286 - accuracy: 0.9615
Epoch 2/3
60000/60000 [==============================] - 11s 182us/sample - loss: 0.0830 - accuracy: 0.9745
Epoch 3/3
60000/60000 [==============================] - 11s 182us/sample - loss: 0.0594 - accuracy: 0.9811


In [65]:
model3.evaluate(test_x,test_y)
#결과값으로 loss와 정확도를 출력해준다.

10000/10000 [==============================] - 1s 98us/sample - loss: 0.0683 - accuracy: 0.9787


[0.0683352321411483, 0.9787]

## 4. Subclassing Keras Model Class
---

In [66]:
## 경북대에서 딥러닝 강의를 해주신 황창하교수님은 이방법을 별로 추천하지 않는다고 하심.

In [67]:
import tensorflow as tf
import numpy as np

In [68]:
(train_x,train_y) , (test_x,test_y) = tf.keras.datasets.mnist.load_data()

In [81]:
train_x,test_x = train_x/255.0 , test_x/255.0 
# tf.cast를 쓰면 작동이 안됨! 타입이 다름.
# tf.cast 는 모델을 Sequential() 로 정의할때만 사용

In [71]:
epochs = 3

In [75]:
class Mymodel(tf.keras.Model): #tf.keras.Model 의 능력 계승
    def __init__(self,num_classes=10): #초기값 설정
        super(Mymodel,self).__init__() # Model 그 위의 클래스(슈퍼클래스)에서 상속 받는다는 의미.
        #즉 클래스를 사용하는 입장에서 전체 클래스의 상속 구조를 이해하지 못하였어도, 문제없이 사용가능.
        
        #define your layers here.
        
        inputs = tf.keras.Input(shape=(28,28))
        self.x0 = tf.keras.layers.Flatten()
        self.x1 = tf.keras.layers.Dense(512,activation='relu',name='d1')
        self.x2 = tf.keras.layers.Dropout(0.2)
        self.predictions = tf.keras.layers.Dense(10,activation='softmax',name='d2')
        
        #변수들을 다 생성한거임. 초기값 생성.
        
    def call(self,inputs):
        # This is where to define your forward pass
        # using the layers previously defined in `__init__`
        
        x = self.x0(inputs) #functional api처럼 생김. 위에서 정의한 내용 사용.
        x = self.x1(x)
        x = self.x2(x)
        return self.predictions(x)

In [76]:
model4 = Mymodel()

In [73]:
batch_size=32

In [77]:
steps_per_epoch = int(len(train_x)/batch_size)
print(steps_per_epoch)

1875


In [79]:
model4.compile(optimizer=tf.keras.optimizers.Adam(),loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [82]:
model4.fit(train_x,train_y,batch_size=batch_size, epochs=epochs)

Train on 60000 samples
Epoch 1/3
60000/60000 [==============================] - 12s 207us/sample - loss: 0.8954 - accuracy: 0.7727
Epoch 2/3
60000/60000 [==============================] - 12s 194us/sample - loss: 0.3905 - accuracy: 0.8896
Epoch 3/3
60000/60000 [==============================] - 10s 172us/sample - loss: 0.3290 - accuracy: 0.9059


In [86]:
model4.evaluate(test_x,test_y)

10000/10000 [==============================] - 1s 105us/sample - loss: 43.3893 - accuracy: 0.8526


[43.389333847609166, 0.8526]

## 5. MLP Using Tensorflow 2.1 Version
---

In [40]:
#교수님이 개인적으로 가장 선호하는 방식
import tensorflow as tf
(x_train,y_train) , (x_test,y_test) = tf.keras.datasets.mnist.load_data()

x_train = tf.cast(x_train.reshape(-1,784),tf.float32)/255.0
x_test = tf.cast(x_test.reshape(-1,784),tf.float32)/255.0
# tf.cast는 one-hot vector로 만들때도 사용한다.

In [41]:
# 클래스 변수 y를 one-hot 벡터로 만든다.
y_train = tf.keras.utils.to_categorical(y_train,10) #dtype=float32
y_test = tf.keras.utils.to_categorical(y_test,10)

In [42]:
n_input = 784
n_hidden1 = 512
n_hidden2 = 256
n_output = 10

lr_rate = tf.constant(0.001,tf.float32) 
# 여름방학에 한 내용. 0.001이라는 상수를 0차원 tensor로 받음.

In [43]:
lr_rate

<tf.Tensor: shape=(), dtype=float32, numpy=0.001>

In [44]:
# 가중치 및 편향 초기화 : Glorot 방법 이용
glorot_init = tf.initializers.glorot_uniform(seed=42)

In [45]:
# 가중치 1,2,3 초기화 (weight, 계수,방향벡터)
w_h1 = tf.Variable(glorot_init((n_input,n_hidden1))) # Variable 그릇에 초기값을 주면서,
# input노드와 output노드를 결정. (행,열) 
# // -> y = XW + b 임 //
w_h2 = tf.Variable(glorot_init((n_hidden1,n_hidden2)))
w_out = tf.Variable(glorot_init((n_hidden2,n_output)))

In [46]:
# 편향 1,2,3 초기화 (bias, 절편)
b_1 = tf.Variable(glorot_init((n_hidden1,))) #  y = XW + b 에따라, 왼쪽처럼 그릇설정.
b_2 = tf.Variable(glorot_init((n_hidden2,)))
b_out = tf.Variable(glorot_init((n_output,)))

In [47]:
#가중치 및 편향을 하나로 묶음.

variables = [w_h1, b_1, w_h2, b_2, w_out, b_out]

In [48]:
# 학습 관련 함수 정의

def feed_forward(x) :
    #layer1 , 2 , output layer
    layer1 = tf.nn.sigmoid(tf.add(tf.matmul(x,w_h1),b_1)) #sigmoid 사용
    layer2 = tf.nn.sigmoid(tf.add(tf.matmul(layer1,w_h2),b_2))
    output = tf.nn.softmax(tf.add(tf.matmul(layer2,w_out),b_out))
    return output

def loss_ftn(y_pred,y_true):
    #loss = tf.compat.v2.nn.sparse_softmax_cross_entropy_with_logits(labels=y_true, logits=y_pred)    
    loss = tf.reduce_mean(-tf.reduce_sum(y_true* tf.math.log(y_pred),axis=[1]))
    
    # softmax loss ftn 임. reduce_sum(,axis=[1]) 은 모든 클래스들에 대해(열) 더하라는 뜻.
    # 또는, 가장 안쪽벡터에 대해 싸그리 더하라는 말임. -1 로도 옵션받기 가능.
    return loss


def acc_fn(y_pred,y_true):
    y_pred = tf.cast(tf.argmax(y_pred,axis=1),tf.int32)
    y_true = tf.cast(tf.argmax(y_true,axis=1),tf.int32)
    predictions = tf.cast(tf.equal(y_true,y_pred),tf.float32) 
    #float32로 받아야 reduce_mean 이 의미가 있음. 주의!! tf.equal은 같은거 체크해주는 함수.
    
    return tf.reduce_mean(predictions)

def backward_prop(batch_xs,batch_ys) :
    optimizer = tf.keras.optimizers.Adam(learning_rate=lr_rate) 
    #lr_rate는 위에서 0.001로 정의

    with tf.GradientTape() as tape : #미분 해야하는걸 #tf.GradientTape()로 저장해나감. with는 참조함수
        #with 함수를 씀에 유의하자.
        predicted = feed_forward(batch_xs) #batch_xs 는 batch_size만큼 들어올 데이터들
        step_loss = loss_ftn(predicted,batch_ys) #위에서 정의한 손실함수.
        
        grads = tape.gradient(step_loss,variables) 
        # step_loss 는 loss임. 여기서는 batch단위로 실행하기에 step을 붙임. 
        # variables는 위에서 변수로 정의한 parameters set
        # 미분값 = gradient(목적함수, 해당지점의 값)을 구한다. 
        # ex) 엄밀한 표현은 아니지만, gradient(x**5 , 2) => 5*2^4 임. 자세한 내용은 아래 Reference 참고
        
        optimizer.apply_gradients(zip(grads,variables)) #여기까지 해야 미분이 일어남.
        #zip함수를 쓴다. apply_gradients 매소드는 gradient와 해당지점의 값을 동시에 받아 최적화가 이루어지기 때문.
    del tape #참조 끝


In [49]:
n_epochs = 3
batch_size = 128
total_batch = int(len(x_train)/batch_size)
n_shape = x_train.shape[0] #또는 len(x_train) 도 가능.
no_steps = n_shape // batch_size # total_batch가 있는데?
display_step = 1

In [50]:
for epoch in range(n_epochs):
    avg_loss = 0. # 1epoch만큼 학습을 시킬때마다 loss와 acc는 초기화임. 다만, 초기값을 제대로 가지고 있기 때문에 이전 학습의 정보는 반영
    avg_acc = 0.
    for i in range(total_batch):
        batch_xs, batch_ys = x_train[i*batch_size:(i+1)*batch_size],y_train[i*batch_size:(i+1)*batch_size]
        
        pred_ys = feed_forward(batch_xs)
        avg_loss += float(loss_ftn(pred_ys, batch_ys)/no_steps) 
        # 1epoch에 돌아가는 횟수인 no_steps만큼 나눠서 한번 batch 학습의 비중을 줌.
        avg_acc += float(acc_fn(pred_ys, batch_ys) /no_steps) # 정확도도 마찬가지로 계산된다. batch학습의 비중을 주기에 누적합임.
        # 예를들어, 정확도가 0.8 이라는 소리는 batch 묶음이 100묶음이라 할 때, 각 묶음에서 전체정확도는 1/100의 비중을 지님.
        # 그걸 다 더하는 행위로써 최종 정확도가 나옴. 개념을 잡을 때 y값 하나하나(원소 하나하나)를 기준으로 잡으면 명확함.
        ###
        # 쉽게말해 표본평균(batch내 정확도)의 평균임. (동일 가중치이기 때문에 성립.)
        
        backward_prop(batch_xs, batch_ys)

    if epoch % display_step == 0:       # % 는 나머지, //은 몫
        #print('Epoch: {epoch}, Training Loss: {avg_loss}, Training ACC: {avg_acc}')
        print("Training loss and Accuracy after epoch {:02d}: {:.4f} and {:.8f}".format(epoch+1, avg_loss, avg_acc))
        # format 형식의 글자를 입력받으려면 {}는 기본임. 02는 0으로 채울 자리수, d는 정수 f는 소수, s는 문자임.
        # dictionary 처럼 {0:02d} {1:.4f} 로 받을 수 있음. 0과 1은 format에서 받을 변수 이름.
        # 없으면 순차적으로 부여한다는 의미이다.
        # 또는, 아예 없게 {} 만으로 표현 가능. {2d} 이런건 안됨.
        # Training loss and Accuracy after epoch 19: 0.0488 and 0.99151979 

print("Neural Network Training Completed!")        


Training loss and Accuracy after epoch 01: 0.5364 and 0.84613716
Training loss and Accuracy after epoch 02: 0.2536 and 0.92316041
Training loss and Accuracy after epoch 03: 0.2022 and 0.93906920
Neural Network Training Completed!


In [51]:
test_pred_y = feed_forward(x_test)

In [52]:
test_accuracy = acc_fn(test_pred_y,y_test)

In [53]:
print("Accuracy for test data:  {:.8f}".format(test_accuracy)) 

Accuracy for test data:  0.93830001


## 6. Reference
---

- [Gradient Tape](https://www.tensorflow.org/tutorials/customization/autodiff?hl=ko)